efiBootLoader: "grub"

kernel: "vmlinuz-linux-zen"
img: "initramfs-linux-zen.img"
fallback: "initramfs-linux-zen-fallback.img"
timeout: "10"

bootloaderEntryName: "Xeno Linux"

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true
