overwrite: false

prefer_grub_d: false

keep_distributor: true

defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: "saved"
    GRUB_DISABLE_SUBMENU: true
    GRUB_GFXMODE: "auto"
    GRUB_BACKGROUND: "/usr/share/backgrounds/xenolinux/wallpaper.png"
    GRUB_DISABLE_RECOVERY: true
