# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Shell process to configure installed system mkinitcpio presets before initcpio job runs
---
dontChroot: false
timeout: 60
script:
    - "/bin/bash /usr/local/bin/xeno-kernel-preset.sh"
