[greeter]
background=/usr/share/backgrounds/xenolinux/wallpaper.png
theme-name=BlackMATE
icon-theme-name=Papirus-Dark
default-user-image=/usr/share/pixmaps/xeno-logo.png
show-clock=true
clock-format=%H:%M
