[Greeter]
theme-name=BlackMATE
icon-theme-name=Papirus-Dark
draw-user-backgrounds=false
draw-grid=false
show-clock=true
clock-format=%H:%M
background=/usr/share/backgrounds/xenolinux/wallpaper.png
logo=/usr/share/pixmaps/xeno-logo-64.png
show-hostname=true
